config/routes.rb
Rails.application.routes.draw do
  devise_for :modes
  root 'meets#index'

  resources :meets do
    resources :comments
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :meet
  belongs_to :mode
end

app/models/meet.rb
class Meet < ApplicationRecord
  has_many :comments
end

app/models/mode.rb
class Mode < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_mode!
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_mode!

  def new
    @comment = Comment.new
  end

  def create
    @meet = Meet.find(params[:meet_id])

    @comment = Comment.new(comment_params)
    @comment.meet_id = @meet.id
    @comment.mode_id = current_mode.id

    if @comment.save
      redirect_to :back
    else
      render :new
    end
  end

  protected

  def comment_params
    params.require(:comment).permit(:message)
  end
end

app/controllers/meets_controller.rb
class MeetsController < ApplicationController
  before_action :authenticate_mode!

  def index
    @meets = Meet.all
  end

  def new
    @meet = Meet.new
  end

  def show
    @meet = Meet.find(params[:id])
  end

  def edit
    @meet = Meet.find(params[:id])
  end

  def update
    @meet = Meet.find(params[:id])
    @meet.update(meet_params)

    redirect_to meets_path ,notice: "update success"
  end

  def destroy
    @meet = Meet.find(params[:id])
    @meet.destroy

    flash[:alert] = "meetup  deleted"
    redirect_to meets_path
  end

  def create
    @meet = Meet.new(meet_params)
    @meet.save

    redirect_to meets_path
  end

  private

  def meet_params
    params.require(:meet).permit(:title,:description)
  end

end

app/controllers/meetuplist_controller.rb
class MeetuplistController < ApplicationController
  

  def index

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/meets_helper.rb
module MeetsHelper
end

app/helpers/meetuplist_helper.rb
module MeetuplistHelper
end

app/views/common/_navbar.html.erb
<nav class="navbar navbar-default" role="navigation">
    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <a class="navbar-brand" href="/">Meet up </a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav navbar-right">
              <% if !current_mode %>
                  <li><%= link_to("注册", new_mode_registration_path) %> </li>
                  <li><%= link_to("登入", new_mode_session_path) %></li>
                <% else %>
                  <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        Hi!, <%= current_mode.email %>
                        <b class="caret"></b>
                    </a>
                    <ul class="dropdown-menu">
                        <li> <%= link_to("登出", destroy_mode_session_path, method: :delete) %> </li>
                    </ul>
                  </li>
                <% end %>
            </ul>
        </div>
        <!-- /.navbar-collapse -->
    </div>
    <!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Meetup</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "common/navbar" %>
    <%= yield %>
  </body>
</html>

app/views/meets/_comment_form.html.erb
<%= simple_form_for(Comment.new, url: meet_comments_path(@meet)) do |f| %>
   <%= f.input :message %>
   <%= f.button :submit ,'submit'%>
<% end %>

app/views/meets/edit.html.erb
<div class="col-md-4 col-md-offset-4">
    <h2>修改meetup</h2>

    <hr>
    <%= simple_form_for @meet do |f| %>


    <%= f.input :title,label: '标题' %>
    <br>

    <br>
    <%= f.input :description, label: '叙述'%>
    <br>

    <%= f.submit "Submit", :disable_with => 'Submiting...' %>
    <% end %>

 </div>

app/views/meets/index.html.erb
<div class="col-md-12">
    <div class="meet">
      <%= link_to("New meet", new_meet_path, class: "btn btn-primary pull-right") %>
    </div>
    <table class="table table-hover">
      <thead>
        <tr>
          <td>#</td>
          <td>Title</td>
          <td>Description</td>
        </tr>
      </thead>
      <tbody>
        <% @meets.each do |meet| %>
          <tr>
            <td>#</td>
            <td><%= link_to(meet.title, meet_path(meet)) %></td>
            <td><%= meet.description %></td>
            <td>
                <%= link_to("Edit", edit_meet_path(meet), class: "btn btn-sm btn-default")%>
                <%= link_to("Delete", meet_path(meet),    class: "btn btn-sm btn-default",
                            method: :delete, data: { confirm: "Are you sure?" } )%>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
   </div>

app/views/meets/new.html.erb
<div class="col-md-4 col-md-offset-4">
    <h2>新增meetup</h2>

    <hr>
    <%= simple_form_for @meet do |f| %>


    <%= f.input :title,label: '标题' %>
    <br>

    <br>
    <%= f.input :description, label: '叙述'%>
    <br>

    <%= f.submit "Submit", :disable_with => 'Submiting...' %>
    <% end %>

 </div>

app/views/meets/show.html.erb
<div class="col-md-12">
  <div class="panel panel-info">
    <div class="panel-heading">
      <div class="meet">
        <%= link_to("Edit", edit_meet_path(@meet), class: "btn btn-primary pull-right")%>
      </div>

      <h2><%= @meet.title %></h2>

      <p><%= @meet.description %></p>
    </div>
    <div class="panel-body">
      <% if @meet.comments.empty? %>
      <p> 尚未有人留言 </p>
     <% else %>
      <% @floor = 1 %>
      <% @meet.comments.each do |comment| %>
        <%= @floor %>楼
        <div class="col-md-12">
          <p><%= comment.message %></p>
        </div>
        <% @floor = @floor  + 1 %>
        </br>
      <% end%>
     <% end %>


     <%= render 'comment_form' %>
    </div>
  </div>
</div>

app/views/meetuplist/index.html.erb
<h2>你可以的！</h2>